//! Recovery enums and structs shared between runtime and assurance layers.
//!
use serde::{Deserialize, Serialize};

/// Outcome status for a recovery attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum RecoveryStatus {
    Success,
    PartialSuccess,
    Failed,
    Aborted,
    Unsafe,
}

/// Autonomy level for recovery execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RecoveryLevel {
    /// Detection only — no automated recovery.
    Level0DetectionOnly = 0,

    /// Recommend recovery actions to operator.
    Level1Recommend = 1,

    /// Automatic low-risk recovery without approval.
    Level2AutomaticLowRisk = 2,

    /// Automatic recovery after safety validation.
    Level3AutomaticWithValidation = 3,

    /// High-risk recovery requires human approval.
    Level4HumanApproval = 4,
}

/// Failure classification for recovery planning.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum FailureClassification {
    SensorFailure,
    ActuatorFailure,
    ConnectivityFailure,
    ProviderFailure,
    PackageFailure,
    MissionFailure,
    HealthDegradation,
    FleetFailure,
    SwarmFailure,
    SafetyFailure,
    Unknown,
}

/// Recovery strategy kind.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryStrategy {
    Failover,
    DegradedMode,
    SpeedReduction,
    SensorRecalibration,
    ProviderReconnect,
    ConnectivityRestart,
    PackageReload,
    DeviceReinitialize,
    RedundantHardwareSwitch,
    RouteChange,
    MissionPause,
    OperatorAlert,
    FleetReassign,
    SwarmRedistribute,
    Custom(String),
}

/// Self-correction action types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SelfCorrectionAction {
    RecalibrateSensor { sensor: String },
    ReconnectProvider { provider: String },
    RestartConnectivity { channel: String },
    ReloadPackage { package: String },
    ReinitializeDevice { device: String },
    SwitchRedundantHardware { component: String },
    ChangeRoute { route: String },
    ReduceSpeed { limit: String },
    PauseMission,
    EnterMode { mode: String },
    Custom { action: String },
}

/// Operating mode for safe transitions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum OperationalMode {
    NormalMode,
    DegradedMode,
    SafeMode,
    EmergencyMode,
    RecoveryMode,
}

/// Single planned recovery action.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlannedRecoveryAction {
    pub description: String,
    pub strategy: RecoveryStrategy,
    pub correction: Option<SelfCorrectionAction>,
    pub risk: String,
    pub requires_approval: bool,
    pub order: u32,
}

/// Recovery plan generated by the planner.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPlan {
    pub name: String,
    pub failure: String,
    pub classification: FailureClassification,
    pub diagnosis: String,
    pub actions: Vec<PlannedRecoveryAction>,
    pub target_mode: Option<OperationalMode>,
    pub level: RecoveryLevel,
    pub risk: String,
}

/// Recovery policy extracted from declarations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPolicySpec {
    pub name: String,
    pub triggers: Vec<(String, Vec<String>)>,
}

/// Safety-validated recovery action ready for execution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SafeRecoveryAction {
    pub action: PlannedRecoveryAction,
    pub safety_validation: ValidationGateResult,
    pub hardware_verification: ValidationGateResult,
    pub capability_verification: ValidationGateResult,
    pub readiness_validation: ValidationGateResult,
    pub approved: bool,
}

/// Result of a validation gate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ValidationGateResult {
    pub gate: String,
    pub passed: bool,
    pub message: String,
}

/// Outcome of executing a recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryResult {
    pub plan: String,
    pub status: RecoveryStatus,
    pub executed_actions: Vec<String>,
    pub failed_actions: Vec<String>,
    pub verification_outcome: String,
    pub evidence: RecoveryEvidence,
}

/// Evidence collected during recovery.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryEvidence {
    pub failure: String,
    pub diagnosis: String,
    pub plan: String,
    pub safety_validation: String,
    pub recovery_actions: Vec<String>,
    pub outcome: String,
    pub operator_approval: Option<String>,
    pub verification: String,
}

/// Recovery audit record for provenance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAuditRecord {
    pub detected_failure: String,
    pub diagnosis: String,
    pub chosen_recovery: String,
    pub safety_validation_result: String,
    pub recovery_outcome: String,
    pub operator_approval: Option<String>,
    pub verification_outcome: String,
    pub timestamp_hint: String,
}

/// Traceability chain for recovery workflow.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryTraceChain {
    pub failure: String,
    pub diagnosis: String,
    pub recovery_plan: String,
    pub safety_validation: String,
    pub recovery_action: String,
    pub outcome: String,
    pub evidence: String,
}

/// Recovery readiness assessment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReadiness {
    pub recovery_ready: bool,
    pub risk: String,
    pub readiness_score: u32,
    pub blockers: Vec<String>,
}

/// Fleet-level recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FleetRecoveryPlan {
    pub fleet: String,
    pub failed_robot: Option<String>,
    pub actions: Vec<String>,
    pub risk: String,
}

/// Knowledge base entry for recovery patterns (no auto-modification).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryKnowledgeEntry {
    pub failure_pattern: String,
    pub recovery_pattern: String,
    pub success_rate: f64,
    pub recommendation: String,
}

/// Recovery knowledge base for self-improvement recommendations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct RecoveryKnowledgeBase {
    pub entries: Vec<RecoveryKnowledgeEntry>,
}

/// Recovery assurance metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAssuranceMetrics {
    pub recovery_evidence: Vec<RecoveryEvidence>,
    pub recovery_readiness: RecoveryReadiness,
    pub success_rate: f64,
    pub traceability: Vec<RecoveryTraceChain>,
}

/// Composite recovery framework report.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReport {
    pub policies: Vec<RecoveryPolicySpec>,
    pub plans: Vec<RecoveryPlan>,
    pub safe_actions: Vec<SafeRecoveryAction>,
    pub results: Vec<RecoveryResult>,
    pub audit: Vec<RecoveryAuditRecord>,
    pub readiness: RecoveryReadiness,
    pub assurance: RecoveryAssuranceMetrics,
    pub fleet_plans: Vec<FleetRecoveryPlan>,
    pub knowledge: RecoveryKnowledgeBase,
    pub passed: bool,
}

/// Input context for recovery planning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryContext {
    pub issue: String,
    pub diagnosis: Option<String>,
    pub classification: Option<FailureClassification>,
    pub level: RecoveryLevel,
}
