apiVersion: v1
kind: Service
metadata:
  name: twin-cloud
  namespace: spanda-twin-cloud
spec:
  type: ClusterIP
  selector:
    app: twin-cloud
  ports:
    - name: http
      port: 80
      targetPort: http
