apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twin-cloud.fullname" . }}-api-key
  labels:
    {{- include "twin-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPANDA_API_KEY: {{ .Values.apiKey | quote }}
